# Perform continuous integration tests on updates and pull requests
name: Build test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: ci_cache
        key: ${{ runner.os }}-build-${{ hashFiles('scripts/ci-install.sh') }}

    - name: Prepare machine with build tools
      run: ./scripts/ci-install.sh


    - name: Validate python code with static analysis/unittest
      run: ./scripts/ci-klippy-whitebox.sh

    - name: Check whitespace conformance
      run: ./scripts/ci-whitespace.sh 2>&1


    - name: Build data dictionaries and ROMs
      run: ./scripts/ci-build.sh 2>&1


    - name: Test klippy using dicts and configs
      run: ./scripts/ci-klippy-systest.sh


    - name: Upload micro-controller data
      uses: actions/upload-artifact@v2
      with:
        name: data-dict
        path: ci_build/dict
